// 3.0/react-app/src/pages/index/index.tsx
import {  Button, Text } from '@tarojs/components'
import { useLoad } from '@tarojs/taro'
import './index.less'
import { useDispatch, useSelector } from 'react-redux'
import {increment} from '@/store/reducer/counter/counter'

export default function Index() {
  const count = useSelector((state:any)=>state.counter.count)
  const dipatch = useDispatch()
  useLoad(() => {
    console.log('Page loaded.:',count)
  })

  return (
    <>
      <Text>首页</Text>
      <Text>{count}</Text>
      <Button onClick={()=>dipatch(increment())}>count++</Button>
    </>
  )
}

// 3.0/vue3-taro-app/src/pages/index/index.vue
<template>
  <view class="index">
    <text>state:{{ store.count }}</text>
    <text>getter:{{ store.doubleCount }}</text>
    <button @click="c">+1</button>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import './index.less'
import useCounterStore from '@/stores/counter'

const store = useCounterStore()
const c = ()=>{
  console.log(store.count)
}
console.log(store.increment)
</script>
